# Generated by Django 5.0.3 on 2024-04-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0002_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
