# Generated by Django 5.0.3 on 2024-04-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0003_alter_reply_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eg',
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
