# Generated by Django 5.0.3 on 2024-03-14 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_prrof', models.FileField(upload_to='teacher_documents/id')),
                ('id_verify', models.BooleanField(default=False)),
                ('id_block', models.BooleanField(default=False)),
                ('photo_proof', models.FileField(upload_to='teacher_documents/photo')),
                ('photo_verify', models.BooleanField(default=False)),
                ('photo_block', models.BooleanField(default=False)),
                ('tenth_proof', models.FileField(upload_to='teacher_documents/tenth_proof')),
                ('tenth_verify', models.BooleanField(default=False)),
                ('tenth_block', models.BooleanField(default=False)),
                ('plustwo_proof', models.FileField(upload_to='teacher_documents/plustwo_proof')),
                ('plustwo_verify', models.BooleanField(default=False)),
                ('plustwo_block', models.BooleanField(default=False)),
                ('experience_proof', models.FileField(upload_to='teacher_documents/experience_proof')),
                ('experience_verify', models.BooleanField(default=False)),
                ('experience_block', models.BooleanField(default=False)),
                ('graduation_proof', models.BooleanField(default=False)),
                ('graduation_block', models.BooleanField(default=False)),
                ('is_document_verified', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.teacherdetails')),
            ],
        ),
    ]
