# Generated by Django 5.0.3 on 2024-03-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_teacherdocument_teacher_teacherdocument_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pic')),
                ('social_link1', models.CharField(blank=True, max_length=250, null=True)),
                ('social_link2', models.CharField(blank=True, max_length=250, null=True)),
                ('social_link3', models.CharField(blank=True, max_length=250, null=True)),
                ('about', models.TextField()),
                ('current_role', models.CharField(blank=True, max_length=250, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
