# Generated by Django 5.0.3 on 2024-03-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0003_alter_videos_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(default='', upload_to='video/thumbnail'),
            preserve_default=False,
        ),
    ]
