# Generated by Django 5.0.3 on 2024-03-19 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0004_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
