# Generated by Django 5.0.3 on 2024-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0005_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
