# Generated by Django 5.0.3 on 2024-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0006_videos_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='duration',
            field=models.CharField(blank=True, null=True),
        ),
    ]
