# Generated by Django 5.0.3 on 2024-04-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0007_alter_videos_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='rejected_reason',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
