# Generated by Django 5.0.3 on 2024-04-15 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0008_videos_rejected_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='rejected_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
