# Generated by Django 5.0.3 on 2024-04-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0009_alter_videos_rejected_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='demo_video',
            field=models.FileField(blank=True, null=True, upload_to='video/demo_video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='video/thumbnail'),
        ),
    ]
